### ISSUE TITLE
Fatal error: Uncaught PDOException: SQLSTATE[HY000] [2002] Connection refused in /var/www/vendor/laminas/laminas-servicemanager/src/ServiceManager.php on line 672

### ISSUE THREAD

**Issue by goharsahi** [dotkernel/frontend#220]
I'm using Docker with PHP version 7.4 on Windows 10 (using Docker Desktop). I'm unable to open the application in my browser even after various attempts albeit with various configuration changes.

Following code just works perfectly.
```
<?php
$link = mysqli_connect("db", "root", "654321");

if (!$link) {
    echo "Error: Unable to connect to MySQL." . PHP_EOL;
    echo "Debugging errno: " . mysqli_connect_errno() . PHP_EOL;
    echo "Debugging error: " . mysqli_connect_error() . PHP_EOL;
    exit;
}

echo "Success: A proper connection to MySQL was made!" . PHP_EOL;
echo "Host information: " . mysqli_get_host_info($link) . PHP_EOL;
```

Below is the configuration in local.php

```
$databases = [
    'default' => [
        'host' => 'db', // Also tried the IP Address of docker container - 172.18.0.2
        'dbname' => 'dbname',
        'user' => 'dbuser',
        'password' => '654321',
        'port' => 6603,
        'driver' => 'pdo_mysql',
        'charset' => 'utf8mb4',
        'collate' => 'utf8mb4_general_ci'
    ]
    // you can add more database connections into this array
];
```
Also another thing, The Phinx migrations ran perfectly, however, Phinx seeds are not running. Keeps giving the error 'Phinx.yml' not found.

**Comment by Calin23** [comment]
Hi @goharsahi .

Do you have a ```docker-compose.yaml``` file in your root directory?

Example ```docker-compose.yaml``` configuration:

```
version: '3.3'
services:
  db:
    image: mysql/mysql-server:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'dk3'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
      ...
```

And try to use ```127.0.0.1``` in your host configuration.

```
    'default' => [
        'host' => '127.0.0.1',
       ...
```

For Phinx seeds please specify which command you runed.

**Comment by goharsahi** [comment]
docker-compose.yml
```
version: "2"
services:

  web:
    build:
      context: .
      dockerfile: container-build/web/Dockerfile
    environment:
      - MYSQL_DATABASE=dbname
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=654321
      - MYSQL_HOST=db
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
    depends_on:
      - db

  db:
    image: mysql:5.7
    ports:
      - "6603:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=654321
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=654321
      - MYSQL_DATABASE=dbname
    volumes:
      - "mysql_data:/var/lib/mysql"

volumes:
  mysql_data: { driver: local }
```

Seed Command
```
php vendor/bin/phinx seed:run -s seed=data/database/seeds/RoleSeeder
```
Output
```
Phinx by CakePHP - https://phinx.org.


In FileLocator.php line 71:
                                                                                                                                      
  The file "phinx.yml" does not exist (in: "D:\dataD\ziwajun-muneerah\ziwajun_muneerah", "D:\dataD\ziwajun-muneerah\ziwajun_muneerah  
  \").                                                                                                                                
                                                                                                                                      

seed:run [-c|--configuration CONFIGURATION] [-p|--parser PARSER] [-e|--environment ENVIRONMENT] [-s|--seed SEED]
```
